name: graf3dvscode
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - sympy
  - fastapi
  - uvicorn
  - trimesh
  - shapely
  - matplotlib
  - pip
  - pip:
    - "uvicorn[standard]"